name: "Хомяк отчаянного хиппи"
description: "Не покидая пыльных стен"

exclude: ['Gemfile', 'Gemfile.lock', 'makefile']

markdown: redcarpet
highlighter: pygments

paginate: 20
paginate_path: archive/:num
permalink: /:year/:title/
baseurl: /
url: http://madfaill.me

timezone: Europe/Moscow
encoding: "utf-8"

analytics: false
google_analytics: 'UA-XXXXXXXX-X'

disqus: true
disqus_shortname: 'madfaill'

author:
  email: me@madfaill.me
  github: MadFaill
  facebook: MadFaill
  twitter: MadFaill
  name: Nikolay Balakirev

show_drafts: false

excerpt_separator: "<!-- cut -->"

tag_page_layout: tag_page
tag_page_dir: tags

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
