name: 'Не покидая пыльных стен'
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'makefile']
highlighter: true
future: true
disqus: true

paginate: 20
paginate_path: archive/:num

production_url: http://madfaill.me
permalink: /:year/:month/:day/:title

author:
  email: madfaill@gmail.com
  github: https://github.com/MadFaill
  twitter: https://twitter.com/MadFaill
  facebook: https://www.facebook.com/a8h333

# lsi: true
#rss: http://feeds.feedburner.com/rss/
#google_adsense: true
#google_analytics: true
#ga_id: